apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: etlo472fc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: etlo472fc-go 
  name: etlo472fc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: etlo472fc-go 
